version: "3.9"

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
